### ISSUE TITLE
docker run error

### ISSUE THREAD

**Issue by luoqiz** [abi/screenshot-to-code#454]
![image](https://github.com/user-attachments/assets/affb4f97-10b7-442c-904b-25770e1f4d90)

**Comment by abi** [comment]
Please update tailwind.config.js to tailwind.config.cjs

I'll fix this in the repo soon

**Comment by luoqiz** [comment]
done

**Comment by khuongphp** [comment]
> Please update tailwind.config.js to tailwind.config.cjs
> 
> I'll fix this in the repo soon

And run `docker compose build frontend` after that.

**Comment by xibudadao** [comment]
> Please update tailwind.config.js to tailwind.config.cjs
> 
> I'll fix this in the repo soon

The same error problem, the problem still exists after the change

**Comment by TuanVnit** [comment]
@xibudadao And run docker compose build frontend after that.
